requests:
  backoff_factor: 2
  cookies: {}
  delay:
  - 2
  - 3
  headers:
    User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML,
      like Gecko) Chrome/148.0.0.0 Safari/537.36
  proxies: {}
  retry_times: 3
  timeout: 30
