enabled: false
search:
  mode: api
  timeout: 30
  retry_times: 3
  delay:
  - 3
  - 5
  backoff_factor: 2
  key: ''
  params: {}
novel_info:
  mode: api
  timeout: 30
  retry_times: 3
  delay:
  - 3
  - 5
  backoff_factor: 2
  key: ''
  params: {}
chapter_list:
  mode: api
  timeout: 30
  retry_times: 3
  delay:
  - 3
  - 5
  backoff_factor: 2
  key: ''
  params: {}
chapter_content:
  mode: api
  timeout: 30
  retry_times: 3
  delay:
  - 3
  - 5
  backoff_factor: 2
  key: ''
  params: {}
