api:
  oiapi:
    backoff_factor: 2
    delay:
    - 3
    - 5
    key: ''
    params: {}
    retry_times: 3
    timeout: 30
  rain:
    backoff_factor: 2
    delay:
    - 2
    - 3
    key: ''
    params: {}
    retry_times: 3
    timeout: 30
browser:
  default:
    backoff_factor: 2
    browser_type: chromium
    delay:
    - 2
    - 5
    headless: false
    retry_times: 3
    timeout: 30
    user_data_dir: app_data\browser\Chromium\User Data
    viewport:
      height: 720
      width: 1280
requests:
  default:
    backoff_factor: 2
    cookies: {}
    delay:
    - 3
    - 5
    headers:
      User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML,
        like Gecko) Chrome/148.0.0.0 Safari/537.36
    proxies: {}
    retry_times: 3
    timeout: 30
