epub:
  compression: deflate
  compresslevel: 9
  css_style: default
  enabled: true
  encoding: utf-8
  file_name_template: '{title}'
  include_toc: true
  jpeg_quality: 85
  max_image_width: 0
  optimize_images: true
  output_path: app_data/exports/{group}/{title}/{file_name_template}
