"""构建时工具：扫描 sources/*/source.json 生成 _manifest.py 供 Nuitka onefile 模式使用。

用法: python -m novelbase.utils.build_manifest

onefile 产物无法扫描文件系统，`source.py` 在编译模式下改读本文件内嵌的
`SOURCES`（目录名 → source.json 内容）与 `SOURCE_DIRS`（source_name → 目录名）。

`sources/` 下 `source_name` 撞名时直接非零退出（编译模式的 `SOURCE_DIRS` 会静默
覆盖、`list_sources()` 会返回重复条目）。

注意：`SOURCES` 存的是 `load_manifest()` 的结果（`common` 已并入各能力段），与
非编译模式下 `get_manifest()` 的返回一致；否则 `capabilities()` 读每段 `mode`
时会 KeyError（真实 source.json 的 mode 放在 common 里）。
"""
from pathlib import Path

from ..sources.manifest import DuplicateSourceNameError, load_manifest, scan_source_names

SRC = Path(__file__).parent.parent / "sources"
OUT = Path(__file__).parent / "_manifest.py"


def build() -> None:
    if not SRC.exists():
        print(f"ERROR: sources dir not found: {SRC}")
        return

    try:
        # 撞名 → DuplicateSourceNameError（编译模式的 SOURCE_DIRS 撞名会静默覆盖，
        # 且编译分支 list_sources() 不去重、会把同一个名字返回两次——必须在构建期拦住）。
        # strict=True 让坏 manifest 也中止；那不是撞名，故不在此捕获：让 ManifestError
        # 自然冒泡，traceback 直接给出真因，避免误报「重复」。
        by_name = scan_source_names([SRC], strict=True)
    except DuplicateSourceNameError as e:
        raise SystemExit(f"ERROR: source_name 重复，构建中止：{e}")

    sources: dict[str, dict] = {}
    source_dirs: dict[str, str] = {}
    for source_name, path in sorted(by_name.items()):
        sources[path.name] = load_manifest(path)
        source_dirs[source_name] = path.name

    lines = [
        "# Auto-generated by novelbase.utils.build_manifest. DO NOT EDIT.",
        "# Nuitka 模式下 source.py 的 list_sources() / get_manifest() / resolve() 读取此文件。",
        "# 删/增书源后重新运行: python -m novelbase.utils.build_manifest",
        "",
        "SOURCES: dict[str, dict] = {",
    ]
    for name, manifest in sources.items():
        lines.append(f"    {name!r}: {manifest!r},")
    lines.append("}")
    lines.append("")
    lines.append("SOURCE_DIRS: dict[str, str] = {")
    for source_name, dirname in sorted(source_dirs.items()):
        lines.append(f"    {source_name!r}: {dirname!r},")
    lines.append("}")
    lines.append("")

    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"Generated {OUT} ({len(sources)} sources)")


if __name__ == "__main__":
    build()
