"""构建时工具：扫描 sources/*/source.json 生成 _manifest.py 供 Nuitka onefile 模式使用。

用法: python -m novelbase.utils.build_manifest

onefile 产物无法扫描文件系统，`source.py` 在编译模式下改读本文件内嵌的
`SOURCES`（目录名 → source.json 内容）与 `SOURCE_DIRS`（source_name → 目录名）。

注意：`SOURCES` 存的是 `load_manifest()` 的结果（`common` 已并入各能力段），与
非编译模式下 `get_manifest()` 的返回一致；否则 `capabilities()` 读每段 `mode`
时会 KeyError（真实 source.json 的 mode 放在 common 里）。
"""
import os
from pathlib import Path

from ..sources.manifest import load_manifest

SRC = Path(__file__).parent.parent / "sources"
OUT = Path(__file__).parent / "_manifest.py"


def build() -> None:
    if not SRC.exists():
        print(f"ERROR: sources dir not found: {SRC}")
        return

    sources: dict[str, dict] = {}
    source_dirs: dict[str, str] = {}
    for entry in sorted(os.listdir(SRC)):
        if entry.startswith("_") or entry == "__pycache__":
            continue
        d = SRC / entry
        if not d.is_dir() or not (d / "source.json").is_file():
            continue
        manifest = load_manifest(d)
        sources[entry] = manifest
        source_dirs[manifest["source_name"]] = entry

    lines = [
        "# Auto-generated by novelbase.utils.build_manifest. DO NOT EDIT.",
        "# Nuitka 模式下 source.py 的 list_sources() / get_manifest() / resolve() 读取此文件。",
        "# 删/增书源后重新运行: python -m novelbase.utils.build_manifest",
        "",
        "SOURCES: dict[str, dict] = {",
    ]
    for name, manifest in sources.items():
        lines.append(f"    {name!r}: {manifest!r},")
    lines.append("}")
    lines.append("")
    lines.append("SOURCE_DIRS: dict[str, str] = {")
    for source_name, dirname in sorted(source_dirs.items()):
        lines.append(f"    {source_name!r}: {dirname!r},")
    lines.append("}")
    lines.append("")

    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"Generated {OUT} ({len(sources)} sources)")


if __name__ == "__main__":
    build()
