"""构建时工具：扫描 sources/ 生成 _manifest.py 供 Nuitka 模式使用。

用法: python -m novelbase.utils.build_manifest

生成 novelbase/utils/_manifest.py，内容包含所有书源的静态元数据，
Nuitka onefile 无法扫描文件系统时读取此文件替代。
"""
import os
from pathlib import Path

from ..source import _scan_capabilities

SRC = Path(__file__).parent.parent / "sources"
OUT = Path(__file__).parent / "_manifest.py"


def _read_constants(init_path: Path) -> dict:
    """读取 __init__.py 中的模块级常量（NAME, SHOW_NAME, HOSTS 等）。"""
    constants = {}
    with init_path.open("r", encoding="utf-8") as f:
        source = f.read()
    # 用 exec 在当前命名空间执行，提取常量
    ns = {}
    exec(source, ns)
    for key in ("NAME", "SHOW_NAME", "HOSTS"):
        val = ns.get(key)
        if val is not None:
            constants[key.lower()] = val
    return constants


def build():
    """扫描 sources/ 目录，生成 _manifest.py。"""
    if not SRC.exists():
        print(f"ERROR: sources dir not found: {SRC}")
        return

    sources_data = {}
    for entry in sorted(os.listdir(SRC)):
        if entry.startswith("_") or entry == "__pycache__":
            continue
        pkg_dir = SRC / entry
        if not pkg_dir.is_dir() or not (pkg_dir / "__init__.py").exists():
            continue

        # 读取常量
        consts = _read_constants(pkg_dir / "__init__.py")

        # 扫描能力矩阵
        caps = _scan_capabilities(pkg_dir)

        # 序列化 hosts 为 list
        if "hosts" in consts and isinstance(consts["hosts"], tuple):
            consts["hosts"] = list(consts["hosts"])

        sources_data[entry] = {
            "meta": consts,
            "modes": caps,
        }

    # 生成 Python 源码
    lines = [
        "# Auto-generated by novelbase.tools.build_manifest. DO NOT EDIT.",
        "# Nuitka 模式下 register_source() / capabilities() 读取此文件。",
        "# 删/增书源后重新运行: python -m novelbase.tools.build_manifest",
        "",
        "_SOURCES = {",
    ]

    for name, data in sources_data.items():
        meta = data["meta"]
        lines.append(f"    {name!r}: {{")
        lines.append(f"        'meta': {{")
        for k, v in meta.items():
            lines.append(f"            {k!r}: {v!r},")
        lines.append(f"        }},")
        lines.append(f"        'modes': {data['modes']!r},")
        lines.append(f"    }},")

    lines.append("}")
    lines.append("")

    # 兼容旧代码：flat_sources 格式
    lines.append("def _flat_sources():")
    lines.append("    '''返回 flat_sources 格式，与旧 _scan_sources() 输出一致。'''")
    lines.append("    result = {}")
    lines.append("    for name, data in _SOURCES.items():")
    lines.append("        meta = data['meta']")
    lines.append("        result[name] = {")
    lines.append("            'name': meta.get('name', name),")
    lines.append("            'show_name': meta.get('show_name', name),")
    lines.append("            'hosts': tuple(meta.get('hosts', [])),")
    lines.append("        }")
    lines.append("    return result")
    lines.append("")

    with OUT.open("w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    print(f"Generated {OUT} ({len(sources_data)} sources)")


if __name__ == '__main__':
    build()
